// src/components/KeySwitchItem.tsx
import { z } from 'zod';
import { ProductResult } from '../utils/schemas';
import ShopifyImage from './ShopifyImage.tsx';
import { cn } from '@/lib/utils.ts';
import { Button } from './button.tsx';
import { ShoppingCart } from 'lucide-react';
import { useStore } from '@nanostores/react';
import { $cart, $isCartUpdating, addCartItem } from '@/stores/cart.ts';

interface Props {
  product: z.infer<typeof ProductResult>;
}

export function KeySwitchItem({ product }: Props) {
  const variant = product!.variants.nodes[0];
  const price = new Intl.NumberFormat('de-CH', {
    style: 'currency',
    currency: variant.price.currencyCode,
  }).format(Number(variant.price.amount));
  const cart = useStore($cart);
  const isCartUpdating = useStore($isCartUpdating);

  async function handleClickAddToCart(variantId: string) {
    await addCartItem({ id: variantId, quantity: 10 });
  }

  return (
    <a
      href={`/switches/${product!.handle}`}
      className="flex h-[150px] w-[100px] flex-col rounded-md p-2 font-bold backdrop-blur-sm"
      tabIndex={0}
      role="button"
    >
      <ShopifyImage
        classList="z-10 overflow-hidden object-cover flex-none hover:translate-y-2 transition-transform"
        loading="eager"
        image={product!.images.nodes[0]}
        sizes={`100px`}
      />
      <div className="ms-1 flex flex-1 flex-col gap-1">
        <span className="max-h-[30px] overflow-hidden text-xs">{product!.title}</span>
        <div className="flex gap-1">
          <div className={cn('h-2 w-2 self-center rounded-full', variant.availableForSale ? 'bg-green-700' : 'bg-red-700')}></div>
          <span className="text-xs">{price}</span>
          <Button
            variant="ghost"
            disabled={!!cart?.id || isCartUpdating}
            onClick={(e) => {
              e.preventDefault();
              e.stopPropagation();
              handleClickAddToCart(variant.id);
            }}
          >
            <ShoppingCart />
          </Button>
        </div>
      </div>
    </a>
  );
}

// src/components/KeySwitchItem.svelte
<script lang="ts">
  import { z } from 'zod';
  import { ProductResult } from '../utils/schemas';
  import ShopifyImage from './ShopifyImage.svelte';

  interface Props {
    product: z.infer<typeof ProductResult>;
  }

  const { product }: Props = $props();
</script>

<a
  href={`/switches/${product?.handle}`}
  class="relative h-[100px] w-[100px] rounded-lg border-4 border-solid border-primary-default outline-primary-default drop-shadow-xs transition-all focus-within:outline focus-within:drop-shadow-sm hover:drop-shadow-sm focus:drop-shadow-sm"
  tabindex="0"
  role="button"
>
  <div class="absolute z-0 h-full w-full rounded-[5px] bg-secondary-default"></div>
  {#if product}
    <ShopifyImage
      classList="absolute z-10 overflow-hidden h-full object-cover"
      loading="eager"
      image={product.images.nodes[0]}
      sizes={`100px`}
    />
  {/if}
</a>
